name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  verify:
    name: verify
    runs-on: self-hosted
    if: ${{ always() }}
    env:
      #GOPATH: ${{ github.workspace }}
      WORKSPACE: ${{ github.workspace }}/src/github.com/kosmos-io/kosmos
      GOPROXY: "https://goproxy.cn,direct"
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKSPACE }}
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: lint
        run: hack/verify-staticcheck.sh
      - name: vendor
        run: hack/verify-vendor.sh
      - name: codegen
        run: hack/verify-codegen.sh
      - name: crds
        run: hack/verify-crds.sh
  build:
    name: build
    needs: verify
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Compile
        run: make all
  test:
    name: Unit test
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: make test
  e2e:
    name: E2e test
    needs: build
    env:
      GOPROXY: "https://goproxy.cn,direct"
    runs-on: self-hosted
    steps:
      # Free up disk space on Ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Prepare e2e env
        run: ./hack/prepare-e2e.sh
      - name: Run e2e test
        run: ./hack/rune2e.sh
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: kosmos-e2e-logs-${{ github.run_id }}
          path: ${{ github.workspace }}/e2e-test/logs-*